# Generated by Django 6.0.7 on 2026-07-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kura_park', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения граждан'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя отправителя'),
        ),
    ]
