# Generated by Django 6.0.7 on 2026-07-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kura_park', '0002_alter_feedback_options_feedback_is_processed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Альтернативный текст (alt)')),
                ('description', models.CharField(max_length=250, verbose_name='Описание на слайде')),
                ('image', models.ImageField(upload_to='slider_images/', verbose_name='Изображение слайда')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
            ],
            options={
                'verbose_name': 'Слайд парка',
                'verbose_name_plural': 'Слайды на главной',
                'ordering': ['order', 'id'],
            },
        ),
    ]
