# Generated by Django 6.0.7 on 2026-07-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kura_park', '0003_parkslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок новости')),
                ('summary', models.CharField(max_length=500, verbose_name='Краткое описание (для превью)')),
                ('content', models.TextField(verbose_name='Полный текст новости')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
    ]
