# Generated by Django 6.0.7 on 2026-07-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kura_park', '0004_newsarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок / Имя')),
                ('comment', models.TextField(verbose_name='Комментарий / Описание')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Одобрено (отображается на карте)')),
            ],
            options={
                'verbose_name': 'Метка на карте',
                'verbose_name_plural': 'Метки на карте',
                'ordering': ['-created_at'],
            },
        ),
    ]
