# Generated by Django 6.0.7 on 2026-07-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kura_park', '0005_usermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermark',
            name='category',
            field=models.CharField(choices=[('idea', '💡 Предложение / Идея'), ('fix', '🛠 Благоустройство / Починить'), ('place', '🌲 Интересное место')], default='idea', max_length=20, verbose_name='Категория'),
        ),
    ]
